<?php 
//teste wallace
/**
 * Home for my meta tags.
 */
function mymetatags_home() {
  $html = "<p><strong>Hello, <em>meta tags</em> world!<strong>";
  return $html;
  //return MENU_ACCESS_DENIED;
  //return MENU_NOT_FOUND;
  //return MENU_SITE_OFFLINE;

}

/**
 * Listing paths that use the meta tags.
 */
function mymetatags_list_paths() {
  $html = "<p><strong>Hello, <em>meta tags</em> world!<strong>";
  return $html;
  //return MENU_ACCESS_DENIED;
  //return MENU_NOT_FOUND;
  //return MENU_SITE_OFFLINE;
  
}

/**
 * Update paths that use the meta tags.
 */
function mymetatags_update_paths() {
  $html = "<p><strong>Hello, <em>meta tags</em> world!<strong>";
  return $html;
  //return MENU_ACCESS_DENIED;
  //return MENU_NOT_FOUND;
  //return MENU_SITE_OFFLINE;

}