<?php

/*
 * Implements hook permission
 */
function mymetatags_permission() {
  return array(
      'manage page meta tags' => array(
      'title' => t('Manage Page Meta Tags'),
      'description' => t('Manage meta tags created on pages.'),
      )
  );  
}

/**
 * Implements hook_menu().
 */
function mymetatags_menu() {
  $items['admin/config/search/mymetatags'] = array(
      'title' => 'My Meta Tags',
      'description' => 'Meta tags Page',
      'page callback' => 'mymetatags_home',
      'access arguments' => array('manage page meta tags'),
      'type' => MENU_NORMAL_ITEM,
      'weight' => 0,
      'file' => 'mymetatags.pages.inc',
  );
  
  $items['admin/config/search/mymetatags/list'] = array(
      'title' => 'My Meta Tags List Paths',
      'description' => 'List all paths associated with meta tags',
      'page callback' => 'mymetatags_list_paths',
      'access arguments' => array('manage page meta tags'),
      'type' => MENU_DEFAULT_LOCAL_TASK,
      'weight' => 0,
      'file' => 'mymetatags.pages.inc',
  );
  
  $items['admin/config/search/mymetatags/update'] = array(
      'title' => 'My Meta Tags Update Paths',
      'description' => 'Updates all paths associated with meta tags',
      'page callback' => 'mymetatags_update_paths',
      'access arguments' => array('manage page meta tags'),
      'type' => MENU_LOCAL_TASK,
      'weight' => 0,
      'file' => 'mymetatags.pages.inc',
  );

  return $items;
}


//sdsdsd